# Generated by Django 3.0.7 on 2020-07-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
